on: workflow_dispatch

jobs:
  generate_changelog_file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.1.1
      with:
        # see: https://github.com/heinrichreimer/action-github-changelog-generator
        repo: wise-introvert/deepsearchjs
        output: CHANGELOG.md
        issues: true
        pullRequests: true
        issuesWoLabels: false
        unreleased: true
        compareLink: true
        includeLabels: bug,enhancement,documentation,build,packaging,deprecated
        maxIssues: 150
        releaseBranch: release
        verbose: false
        author: true
  commit:
    runs-on: ubunut-latest
    needs: generate_changelog_file
    steps:
      - name: commit
        run: |
          echo "${{needs.generate_changelog_file.outputs.changelog}}" > CHANGELOG.md
          git add CHANGELOG.md
          git commit -m "docs: update changelog"
          git push origin "$BRANCH"
        
