on: workflow_dispatch

jobs:
  generate_changelog_file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.1.1
