on: workflow_dispatch

jobs:
  generate_changelog_file:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: changelog
      uses: heinrichreimer/action-github-changelog-generator@v2.1.1
      with:
        # see: https://github.com/heinrichreimer/action-github-changelog-generator
        repo: wise-introvert/deepsearchjs
        output: CHANGELOG.md
        issues: true
        pullRequests: true
        issuesWoLabels: false
        unreleased: true
        compareLink: true
        includeLabels: bug,enhancement,documentation,build,packaging,deprecated
        maxIssues: 150
        releaseBranch: release
        verbose: false
        author: true
    - name: commit
      needs: changelog
      run: |
        echo "${{needs.changelog.outputs.changelog}}" > CHANGELOG.md
        git add CHANGELOG.md
        git commit -m "docs: update changelog"
        git push origin "$BRANCH"
        
