name: Changelog

on:
  release:
    types:
      - created

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Conventional Changelog Action
      uses: TriPSs/conventional-changelog-action@v3
      with:
        github-token: ${{ secrets.github_token }}
        git-message: 'chore(release): {version}'
